services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"  # Expose port 8000 for the web service
    networks:
      - tradewithappz_network

networks:
  tradewithappz_network:
    driver: bridge
