# Generated by Django 3.2.19 on 2024-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tradingdata',
            name='day_pl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tradingdata',
            name='exp_brokerage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tradingdata',
            name='order_count',
            field=models.IntegerField(null=True),
        ),
    ]
