# Generated by Django 3.2.19 on 2024-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0003_tradingconfigurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='forward_trailing_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingconfigurations',
            name='reverse_trailing_points',
            field=models.IntegerField(default=0),
        ),
    ]
