# Generated by Django 3.2.19 on 2024-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0004_auto_20240501_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='stoploss_limit_diff_value',
            field=models.IntegerField(default=0),
        ),
    ]
