# Generated by Django 3.2.19 on 2024-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0005_tradingconfigurations_stoploss_limit_diff_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingconfigurations',
            name='stoploss_limit_diff_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
