# Generated by Django 3.2.19 on 2024-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0009_rename_stoploss_limit_diff_value_tradingconfigurations_stoploss_limit_slippage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOD_EOD_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(null=True)),
                ('closing_balance', models.IntegerField(null=True)),
                ('withdrwal_amount', models.IntegerField(default=0, null=True)),
                ('deposit_amount', models.IntegerField(default=0, null=True)),
                ('day_p_and_l', models.IntegerField(null=True)),
                ('day_order_count', models.IntegerField(null=True)),
                ('day_exp_brokerage', models.IntegerField(null=True)),
                ('actual_expense', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('trading_date', models.DateField(null=True)),
                ('week_no', models.IntegerField(null=True)),
                ('prev_day_slippage', models.IntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('position_data', models.JSONField(null=True)),
                ('order_data', models.JSONField(null=True)),
                ('fund_data', models.JSONField(null=True)),
            ],
        ),
    ]
