# Generated by Django 3.2.19 on 2024-05-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0010_sod_eod_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod_eod_data',
            name='trading_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
