# Generated by Django 3.2.19 on 2024-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0011_alter_sod_eod_data_trading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod_eod_data',
            name='trading_date',
            field=models.DateField(auto_now=True, null=True, unique=True),
        ),
    ]
