# Generated by Django 3.2.19 on 2024-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0012_alter_sod_eod_data_trading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod_eod_data',
            name='actual_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='day_exp_brokerage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='day_p_and_l',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='prev_day_slippage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='withdrwal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
