# Generated by Django 3.2.19 on 2024-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0013_auto_20240512_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sod_eod_data',
            name='actual_benefit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sod_eod_data',
            name='trading_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
