# Generated by Django 3.2.19 on 2024-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0015_auto_20240517_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='order_quantity_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=10),
        ),
    ]
