# Generated by Django 3.2.19 on 2024-06-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0016_tradingconfigurations_order_quantity_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='reward_ratio',
            field=models.IntegerField(default=0),
        ),
    ]
