# Generated by Django 3.2.19 on 2024-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0017_tradingconfigurations_reward_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingconfigurations',
            name='default_stoploss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
