# Generated by Django 3.2.19 on 2024-06-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0018_alter_tradingconfigurations_default_stoploss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
