# Generated by Django 3.2.19 on 2024-06-05 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0019_tradingconfigurations_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sod_eod_data',
            name='trading_config',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='fyersapi.tradingconfigurations'),
            preserve_default=False,
        ),
    ]
