# Generated by Django 3.2.19 on 2024-06-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0020_sod_eod_data_trading_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod_eod_data',
            name='trading_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fyersapi.tradingconfigurations'),
        ),
    ]
