# Generated by Django 3.2.19 on 2024-06-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0021_alter_sod_eod_data_trading_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingconfigurations',
            old_name='capital_usage_limit',
            new_name='capital_limit_per_order',
        ),
    ]
