# Generated by Django 3.2.19 on 2024-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0023_tradingconfigurations_capital_usage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOrderTempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('premium_price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
