# Generated by Django 3.2.19 on 2024-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0024_openordertempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='openordertempdata',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='openordertempdata',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
