# Generated by Django 3.2.19 on 2024-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0025_auto_20240608_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='openordertempdata',
            name='sl_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
