# Generated by Django 3.2.19 on 2024-06-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0027_openordertempdata_exp_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='openordertempdata',
            name='is_averaged',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sod_eod_data',
            name='averaging_limit',
            field=models.IntegerField(null=True),
        ),
    ]
