# Generated by Django 3.2.19 on 2024-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0028_auto_20240610_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sod_eod_data',
            name='averaging_limit',
        ),
        migrations.AddField(
            model_name='tradingconfigurations',
            name='averaging_limit',
            field=models.IntegerField(null=True),
        ),
    ]
