# Generated by Django 3.2.19 on 2024-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0029_auto_20240610_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='scalping_amount_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingconfigurations',
            name='scalping_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradingconfigurations',
            name='scalping_stoploss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
