# Generated by Django 3.2.19 on 2024-06-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0030_auto_20240612_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='scalping_ratio',
            field=models.IntegerField(null=True),
        ),
    ]
