# Generated by Django 3.2.19 on 2024-06-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0031_tradingconfigurations_scalping_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='starddle_amount_limit',
            field=models.IntegerField(null=True),
        ),
    ]
