# Generated by Django 3.2.19 on 2024-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0032_tradingconfigurations_starddle_amount_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingconfigurations',
            old_name='starddle_amount_limit',
            new_name='straddle_amount_limit',
        ),
        migrations.AddField(
            model_name='tradingconfigurations',
            name='straddle_capital_usage',
            field=models.IntegerField(null=True),
        ),
    ]
