# Generated by Django 3.2.19 on 2024-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0033_auto_20240622_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='over_trade_status',
            field=models.BooleanField(default=False),
        ),
    ]
