# Generated by Django 3.2.19 on 2024-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0034_tradingconfigurations_over_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='averaging_qty',
            field=models.IntegerField(default=0),
        ),
    ]
