# Generated by Django 3.2.19 on 2024-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyersapi', '0035_tradingconfigurations_averaging_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingconfigurations',
            name='active_broker',
            field=models.CharField(choices=[('DHAN', 'DHAN'), ('FYERS', 'FYERS')], default='DHAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradingconfigurations',
            name='order_quantity_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='DHAN', max_length=10),
        ),
    ]
